//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by cindex.rc
//
#define ERR_INTERNALERR                 1
#define ERR_RECREADERR                  2
#define ERR_DISKFULLERR                 3
#define ERR_RECWRITEERR                 4
#define ERR_INDEXFULLERR                5
#define ERR_INDEXCLOSERR                6
#define ERR_BADPREFSFOLDER              7
#define ERR_BADDATAFOLDER               7
#define ERR_FILESYSERR                  8
#define ERR_UNKNOWNFILERR               9
#define ERR_FILEVERSERR                 10
#define ERR_IMPORTREADERR               11
#define ERR_BADEXPERR                   12
#define ERR_REFORDERERR                 13
#define ERR_MEMERR                      14
#define ERR_RECNOTFOUNDERR              15
#define ERR_WRITEERR                    16
#define ERR_LONGENTRYERR                17
#define ERR_RECNOTEXISTERR              18
#define ERR_RECNOTINVIEWERR             19
#define ERR_RECMATCHERR                 20
#define ERR_WVERSIONERR                 21
#define ERR_TOOFEWCHARFIELD             22
#define ERR_TOOMANYCHARFIELD            23
#define ERR_BADPATTERNFIELD             24
#define ERR_MISMATCHFIELD               25
#define ERR_BADCODEFIELD                26
#define ERR_EMPTYMAINFIELD              27
#define ERR_BADRANGEFIELD               28
#define ERR_EMPTYPAGEFIELD              29
#define ERR_BADDATE                     30
#define ERR_BADDATERANGE                31
#define ERR_RECRANGERR                  32
#define ERR_BADREPERR                   33
#define ERR_SPELLOPENERR                34
#define INFO_SPLITRECORDS               34
#define ERR_SPELLCLOSERR                35
#define ERR_SPELLOPENUSERERR            36
#define IDS_STRING36                    36
#define ERR_SPELLCLOSEUSERERR           37
#define ERR_SPELLWORDCHECKERR           38
#define ERR_SPELLDICMODERR              39
#define ERR_SPELLUSERDICERR             40
#define ERR_SPELLDELUSERERR             41
#define ERR_SPELLNODBERR                42
#define ERR_SPELLWORDOPERR              43
#define ERR_SPELLDICEXISTERR            44
#define ERR_RECMARKERR                  45
#define ERR_BADNUMERR                   46
#define ERR_INVALPAGERANGE              47
#define ERR_NOROOM                      48
#define ERR_TAGSAVE                     49
#define ERR_TAGOVERFLOW                 50
#define ERR_TAGOPEN                     51
#define ERR_BADABBREVERR                52
#define ERR_BADITEMTEXT                 53
#define ERR_RECOVERFLOW                 54
#define ERR_TOOFEWFIELDS                55
#define ERR_TOOMANYFIELDS               56
#define ERR_ABBBADPASTE                 57
#define ERR_GROUPCREATEERR              58
#define ERR_CBCOPY                      59
#define ERR_FONTBADSUB                  60
#define ERR_FONTMISSING                 61
#define ERR_NOLOCATORRANGE              62
#define ERR_OPENERR                     65
#define ERR_OVERWRITEOPEN               66
#define ERR_DUPABBREV                   67
#define ERR_BREAKPAGEFIELD              68
#define ERR_BREAKPROTECTEDFIELD         68
#define ERR_VALUETOOLARGE               69
#define ERR_SPANTOOLARGE                70
#define ERR_INVALLOCATORRANGE           71
#define ERR_PRINTFAIL                   72
#define ERR_PRINTSETUPFAIL              73
#define ERR_ABBOPEN                     74
#define ERR_TOOMANYREFS                 75
#define ERR_DUPKEY                      76
#define ERR_DUPCOPY                     77
#define ERR_INVALSTYLESHEET             78
#define ERR_VERTMARGINS                 79
#define ERR_HORIZMARGINS                80
#define ERR_BADNEWFILERR                81
#define ERR_BADARCHIVE                  82
#define ERR_BADPASS                     95
#define ERR_FILEALREADYOPEN             96
#define ERR_NOWRITEACCESS               97
#define ERR_BADTAGSETNAME               98
#define ERR_FATALDAMAGE                 99
#define ERR_DAMAGEDRECORD               100
#define ERR_NOCONNECTION                101
#define ERR_UNABLETOREVERT              102
#define ERR_NEWVERSERROR                103
#define ERR_NEWVERSERR                  103
#define IDC_RIGHTPOINTER                104
#define ERR_NOFONT                      104
#define ERR_BADXML                      105
#define IDC_DOWNARROW                   106
#define ERR_CONVERSIONERR               106
#define ERR_RECORDSYNTAXERR             107
#define ERR_MISSINGCROSSREF             108
#define ERR_NOCHARMAP                   109
#define IDI_CINDEX                      111
#define IDI_INDEX                       112
#define IDI_XMLRECORDS                  113
#define IDI_ARCHIVE                     114
#define IDI_ABBREV                      115
#define IDI_STYLE                       116
#define IDI_TPL                         117
#define IDI_INDEX_OLD                   118
#define IDI_STYLE_OLD                   119
#define IDI_TPL_OLD                     120
#define IDI_ABBREV_OLD                  121
#define IDR_MODTOOLS                    132
#define IDR_VIEWTOOLS                   134
#define IDD_ABOUTCINDEX                 140
#define IDD_RECORDSTRUCTURE             145
#define IDD_PRINTPROGRESS               146
#define IDD_FIND                        147
#define IDD_REPLACE                     148
#define IDD_GOTO                        149
#define IDD_PRINT                       150
#define IDD_SAVEGROUP                   151
#define IDD_MANAGEGROUPS                152
#define IDD_OTHERFONT                   153
#define IDD_NEW_OPTBUTTON               154
#define IDD_SAVEAS_OPTIONBUTTON         155
#define IDD_WRITE_UNFORM                157
#define IDD_WRITE_FORM                  158
#define IDD_SORT_TEXT                   159
#define IDD_SORT_FIELDS                 160
#define IDD_SORT_REFS                   161
#define IDD_SPELL                       162
#define IDD_SPELL_OPTIONS               163
#define IDD_SPELL_NEWDIC                164
#define IDD_SPELL_EDITDIC               165
#define IDD_VERIFY                      166
#define IDD_RECONCILE                   167
#define IDD_COMPRESS                    169
#define IDD_ALTER                       170
#define IDD_COUNT                       172
#define IDD_STATISTICS                  173
#define IDD_REFSYNTAX                   174
#define IDD_MARGCOL                     175
#define IDD_HEADFOOT                    176
#define IDD_GROUPENTRIES                177
#define IDD_STYLELAYOUT                 178
#define IDD_HEADINGS                    180
#define IDD_CROSSREFS                   181
#define IDD_PAGEREFS                    183
#define IDD_TEXTSTYLE                   184
#define IDD_LOCATORSTYLE                185
#define IDD_STYLEDSTRINGS               186
#define IDD_AUTOGEN                     187
#define IDD_FIND_STYLE                  188
#define IDD_TAG_SETNAME                 190
#define IDD_TAGS_MAIN                   191
#define IDD_TAGS_STRUCT                 192
#define IDD_TAGS_STYLE                  193
#define IDD_TAGS_FONT                   194
#define IDD_TAGS_SPECIAL                195
#define IDD_USERID                      198
#define IDD_OPENARCHIVE                 199
#define IDD_ABBREV                      200
#define SPLASH                          206
#define IDD_SPLASH                      207
#define IDD_CHARTOOL                    215
#define IDD_CODETRANS                   216
#define IDD_FONTSUB                     217
#define IDD_HOTKEYS                     236
#define IDD_RECORDSIZE                  238
#define IDD_PREFS_PGEN                  240
#define IDD_PREFS_PEDIT                 241
#define IDD_PREFS_PTEXT                 242
#define IDD_PREFS_PFORMAT               243
#define IDD_PPREFS_FOLDERS              244
#define IDD_PPREFS_ADMIN                245
#define IDD_REPLACE_STYLE               250
#define IDD_GROUP_INFO                  254
#define IDD_ABOUTDEMO                   255
#define IDD_MACRO_NAME                  255
#define IDR_POPUPS                      260
#define IDD_MANAGECROSSREFS             270
#define IDD_FILTERRECORDS               271
#define IDB_BITMAP1                     272
#define SPLASH_PUB                      272
#define IDD_CREDITS                     273
#define IDD_TAGS_STRUCT1                274
#define IDD_TAGS_XMLSTRUCT              274
#define IDD_TAGS_XMLOTHER               275
#define IDD_FLIPWORDS                   278
#define IDD_ABBREV_MANAGE               279
#define IDD_SPLIT                       280
#define IDD_CHECK_BASIC                 281
#define IDD_CHECK_HEADINGS              282
#define IDD_CHECK_REFS                  283
#define IDD_FIND_STYLE1                 284
#define WARN_BADCONFIG                  300
#define WARN_MISSINGFONT                300
#define WARN_MISSINGRECORDS             301
#define WARN_CORRUPTINDEX               302
#define WARN_RECFIELDNUMWARN            303
#define IDB_PROPAGATE                   303
#define WARN_RECENLARGESIZE             304
#define IDB_BRACES                      304
#define WARN_IMPORTERRORSWARN           305
#define IDB_BRACKETS                    305
#define WARN_DUPGROUPWARNING            306
#define IDB_FLIP                        306
#define WARN_NODIC                      307
#define IDB_HALFFLIP                    307
#define WARN_SQUEEZE                    308
#define IDB_SWAPPAREN                   308
#define WARN_EXPAND                     309
#define IDB_DEFFONT                     309
#define WARN_CROSSSORT                  310
#define IDB_BOLD                        310
#define WARN_DUPTAGSET                  311
#define IDB_ITAL                        311
#define WARN_DELTAGSET                  312
#define IDB_ULINE                       312
#define WARN_EXISTABBREV                313
#define IDB_PREV                        313
#define WARN_SAVEABBREV                 314
#define IDB_NEXT                        314
#define WARN_CLEARABBREV                315
#define IDB_DUPNEW                      315
#define WARN_CODETRANSLATION            316
#define IDB_REVERT                      316
#define WARN_FONTGAPS                   317
#define WARN_CONVERTINDEX               318
#define IDB_NEW                         318
#define IDB_LABEL                       319
#define WARN_RECCHANGED                 320
#define IDB_DELETE                      320
#define WARN_NEGADJUST                  321
#define IDB_ALLRECS                     321
#define WARN_BADIMPORTTYPE              322
#define IDB_FULLFORMAT                  322
#define WARN_INDEXINUSE                 323
#define IDB_DRAFTFORMAT                 323
#define WARN_ALTNOTINDIC                324
#define IDB_INDENTED                    324
#define WARN_DAMAGEDINDEX               325
#define IDB_RUNIN                       325
#define WARN_REVERT                     326
#define IDB_SORTALPHA                   326
#define WARN_DELETEDIC                  327
#define IDB_SORTPAGE                    327
#define WARN_SHORTRECORD                328
#define IDB_SORTNONE                    328
#define WARN_OVERWRITEINDEX             329
#define WARN_DAMAGEDGROUPS              330
#define WARN_BADEXTENSION               331
#define WARN_BADFILETYPE                332
#define IDD_SORT_SUBSTITUTES            332
#define WARN_EMPTYRECORD                333
#define WARN_CONFLICTINGESPARATORS      334
#define WARN_SPLIT                      335
#define WARN_DEMOTEFIELD                336
#define IDD_WRITE_FORM_EXTRAS           336
#define WARN_DEMOTEENLARGE              337
#define IDB_BITMAP2                     341
#define IDB_PROPAGATE_OFF               342
#define IDB_BRACES_OFF                  343
#define IDB_BRACKETS_OFF                344
#define IDB_FLIP_OFF                    345
#define IDB_HALFFLIP_OFF                346
#define IDB_SWAPPAREN_OFF               347
#define IDB_DEFFONT_OFF                 348
#define IDB_BOLD_OFF                    349
#define INFO_BADCONFIG                  349
#define IDB_ITAL_OFF                    350
#define INFO_NOMOREREC                  350
#define IDB_ULINE_OFF                   351
#define INFO_READONLY                   351
#define IDB_PREV_OFF                    352
#define INFO_REPLACEMARKED              352
#define IDB_NEXT_OFF                    353
#define INFO_REPLACECOUNT               353
#define IDB_DUPNEW_OFF                  354
#define INFO_WRITEREC                   354
#define IDB_REVERT_OFF                  355
#define INFO_VERIFYOK                   355
#define INFO_RECGENNUMINFO              356
#define INFO_NONGENNUMINFO              357
#define INFO_RECGENSKIPINFO             358
#define INFO_LASTPAGE                   359
#define INFO_ALLFONTSUSED               360
#define INFO_FILESTATS                  361
#define INFO_IMPORTMARKED               362
#define INFO_SORTORDER                  363
#define INFO_FULLGROUP                  364
#define INFO_CORRUPTINDEX               365
#define INFO_RECCONVERT                 366
#define INFO_NORECCONVERT               367
#define INFO_INDEXNEEDSREPAIR           368
#define INFO_REPAIRMARKED               369
#define INFO_CINUPTODATE                370
#define INFO_UPDATEAVAILABLE            371
#define INFO_WRITERECWITHERROR          372
#define INFO_CONVERSIONCHANGES          373
#define PRG_VERIFYING                   400
#define PRG_SUMMARY                     401
#define PRG_CHECKING                    402
#define PRG_READSORT                    403
#define PRG_SAVING                      404
#define PRG_ADJUSTING                   405
#define PRG_GENERATING                  406
#define PRG_SORTING                     407
#define PRG_NULL                        408
#define PRG_RECONCILING                 409
#define PRG_CONVERTING                  410
#define PRG_PRINTING                    411
#define IDC_RECORDSTRUCT_MAX            1000
#define IDC_RECORDSTRUCT_MINF           1001
#define IDC_RECORDSTRUCT_MAXF           1002
#define IDC_RECORDSTRUCT_FNAME          1006
#define IDC_RECORDSTRUCT_PAT            1007
#define IDC_RECORDSTRUCT_CMIN           1010
#define IDC_RECORDSTRUCT_CMAX           1011
#define IDC_RECORDSTRUCT_TAB            1012
#define IDC_RECORDSTRUCT_CUR            1013
#define IDC_RECORDSTRUCT_CURLEN         1014
#define IDC_ABOUTCINDEX_SUPPORT         1015
#define IDC_ABOUTCINDEX_VER             1016
#define IDC_ABOUTCINDEX_USER            1017
#define IDC_ABOUTCINDEX_ORG             1018
#define IDC_ABOUTCINDEX_SER             1019
#define IDC_PRINTPROGRESS_PAGE          1020
#define IDC_GOTO_TEXT                   1021
#define IDC_GOTO_RECORD                 1022
#define IDC_GOTO_PAGE                   1023
#define IDC_FIND_USERID                 1027
#define IDC_FIND_FINDALL                1028
#define IDC_FIND_ALL                    1029
#define IDC_FIND_SELECTED               1030
#define IDC_FIND_RANGE                  1031
#define IDC_FIND_RANGESTART             1032
#define IDC_FIND_RANGEEND               1033
#define IDC_FIND_ALLDATES               1034
#define IDC_FIND_DATERANGE              1035
#define IDC_FIND_DATESTART              1036
#define IDC_FIND_DATEEND                1037
#define IDC_FIND_TAGREC                 1038
#define IDC_FIND_NEWREC                 1039
#define IDC_FIND_MODREC                 1040
#define IDC_FIND_GENREC                 1041
#define IDC_FIND_DELREC                 1042
#define IDC_FIND_MARKREC                1043
#define IDC_FIND_UP                     1044
#define IDC_FIND_DOWN                   1045
#define IDC_FIND_NOT1                   1046
#define IDC_FIND_TEXT1                  1047
#define IDC_FIND_STYLE1                 1048
#define IDC_FIND_STYLESHOW1             1049
#define IDC_FIND_TAGREC7                1049
#define IDC_FIND_ANDOR1                 1050
#define IDC_FIND_FIELDS1                1051
#define IDC_FIND_EVALREFS1              1052
#define IDC_FIND_WORD1                  1053
#define IDC_FIND_CASE1                  1054
#define IDC_FIND_PATTERN1               1055
#define IDC_FIND_NOT2                   1056
#define IDC_FIND_TEXT2                  1057
#define IDC_FIND_STYLE2                 1058
#define IDC_FIND_STYLESHOW2             1059
#define IDC_FIND_ANDOR2                 1060
#define IDC_FIND_FIELDS2                1061
#define IDC_FIND_EVALREFS2              1062
#define IDC_FIND_WORD2                  1063
#define IDC_FIND_CASE2                  1064
#define IDC_FIND_PATTERN2               1065
#define IDC_FIND_NOT3                   1066
#define IDC_FIND_TEXT3                  1067
#define IDC_FIND_STYLE3                 1068
#define IDC_FIND_STYLESHOW3             1069
#define IDC_FIND_ANDOR3                 1070
#define IDC_FIND_FIELDS3                1071
#define IDC_FIND_EVALREFS3              1072
#define IDC_FIND_WORD3                  1073
#define IDC_FIND_CASE3                  1074
#define IDC_FIND_PATTERN3               1075
#define IDC_FIND_NOT4                   1076
#define IDC_FIND_TEXT4                  1077
#define IDC_FIND_STYLE4                 1078
#define IDC_FIND_STYLESHOW4             1079
#define IDC_FIND_ANDOR4                 1080
#define IDC_FIND_FIELDS4                1081
#define IDC_FIND_EVALREFS4              1082
#define IDC_FIND_WORD4                  1083
#define IDC_FIND_CASE4                  1084
#define IDC_FIND_PATTERN4               1085
#define IDC_PREFS_PGENNOACTION          1087
#define IDC_PREFS_PGENOPEN              1088
#define IDC_PREFS_PGENOPENPANEL         1089
#define IDC_REPLACE                     1090
#define IDC_REPLACE_REP                 1091
#define IDC_REPLACE_TEXT                1092
#define IDC_REPLACE_STYLE               1093
#define IDC_REPLACE_STYLESHOW           1094
#define IDC_PREFS_PGENTIME              1095
#define IDC_PREFS_PGENUIDTEXT           1096
#define IDC_PREFS_PGENUID               1097
#define IDC_PREFS_PGENUPDATE            1098
#define IDC_PREFS_PGENDIRECTORY         1099
#define IDC_PREFS_PGENCINMAX            1100
#define IDC_PREFS_PGENDOCMAX            1101
#define IDC_PREFS_PEDITLACCEPT          1102
#define IDC_PREFS_PEDITLWARN            1103
#define IDC_PREFS_PEDITLFORBID          1104
#define IDC_PREFS_PEDITCARRY            1105
#define IDC_PREFS_PEDITPROPAGATE        1106
#define IDC_PREFS_PEDITMACCEPT          1107
#define IDC_PREFS_PEDITMWARN            1108
#define IDC_PREFS_PEDITMFORBID          1109
#define IDC_PREFS_PEDITTRACK            1110
#define IDC_PREFS_PEDITAUTOTYPE         1111
#define IDC_PREFS_PEDITIGNORESTYLE      1112
#define IDC_PREFS_PEDITRETURN           1113
#define IDC_PREFS_PEDIT_SWITCHVIEW      1114
#define IDC_PREFS_PEDITREMOVEDUP        1115
#define IDC_PREFS_PEDITASAVE            1116
#define IDC_PREFS_PEDITASK              1117
#define IDC_PREFS_PEDITDISCARD          1118
#define IDC_PREFS_PEDITTRACKSOURCE      1119
#define IDC_PREFS_PTEXTFONT             1120
#define IDC_PREFS_PEDIT_NEWWINDOW       1120
#define IDC_PREFS_PTEXTSIZE             1121
#define IDC_PREFS_PEDIT_LABELCHANGESDATE 1121
#define IDC_PREFS_PTEXTSAMPLE           1122
#define IDC_PREFS_PTEXTFCOLOR           1123
#define IDC_PREFS_PTEXTFSHOWFORM        1124
#define IDC_PREFS_PGENRECENT            1126
#define IDC_FONTSIZE_LIST               1127
#define IDC_NEW_OPTIONS                 1128
#define IDC_WRITE_UNFORMDEL             1130
#define IDC_WRITE_UNFORMAPPEND          1131
#define IDC_WRITE_UNFORMNUMORDER        1132
#define IDC_WRITE_UNFORMEXTEND          1133
#define IDC_WRITE_RANGESTART            1134
#define IDC_WRITE_RANGEEND              1135
#define IDC_RECSIZE_NEW                 1136
#define IDC_RECSIZE_CURRENT             1137
#define IDC_RECSIZE_USED                1138
#define IDC_SORT_TEXTSIMPLE             1140
#define IDC_SORT_TEXTCHARPRI            1141
#define IDC_SORT_TEXTIGNH               1142
#define IDC_SORT_TEXTIGNP               1143
#define IDC_SORT_TEXTEVALN              1144
#define IDC_SORT_TEXTPARENPHRASE        1145
#define IDC_SORT_TEXTPAREN              1146
#define IDC_SORT_SCRIPTFIRST            1147
#define IDC_CHECK_B_MIXEDCASE           1147
#define IDC_CHECK_H_INCONSISTENTPREP    1147
#define IDC_CHECK_R_OVERLAPPINGPAGE     1147
#define IDC_SORT_TEXTPREFIX             1148
#define IDC_SORT_FIELDLIST              1149
#define IDC_SORT_FIELDSIGNLOWEST        1150
#define IDC_SORT_REFPRI                 1151
#define IDC_SORT_REFSASCEND             1152
#define IDC_SORT_REFSALL                1153
#define IDC_SORT_REFSEGORDER            1154
#define IDC_PRINT_RECFROM               1155
#define IDC_PRINT_RECTO                 1156
#define IDC_PRINT_ODDEVEN               1157
#define IDC_SORT_REFSTYLEPRI            1157
#define IDC_PRINT_BULLET                1158
#define IDC_SPELL_OPTIONSPDDELETE       1160
#define IDC_SPELL_BADPROMPT             1161
#define IDC_SPELL_NEWREC                1162
#define IDC_SPELL_MODREC                1163
#define IDC_SPELL_FIELD                 1164
#define IDC_SPELL_CHECKPAGE             1165
#define IDC_SPELL_GOODLIST              1167
#define IDC_SPELL_CHANGE                1168
#define IDC_SPELL_ADD                   1169
#define IDC_SPELL_BADWORD               1170
#define IDC_SAVEGROUP_NAME              1170
#define IDC_SPELL_IGNOREALL             1171
#define IDC_MANAGEGROUPS_ALL            1171
#define IDC_SPELL_SUGGEST               1172
#define IDC_MANAGEGROUPS_GROUP          1172
#define IDC_SPELL_LANGUAGE              1173
#define IDC_MANAGEGROUPS_LIST           1173
#define IDC_SPELL_DICTIONARY            1174
#define IDC_MANAGEGROUPS_REBUILD        1174
#define IDC_SPELL_OPTIONS               1175
#define IDC_MANAGEGROUPS_DELETE         1175
#define IDC_SPELL_OPTIONUS              1176
#define IDC_MANAGEGROUPS_LINK           1176
#define IDC_SPELL_OPTIONUKISE           1177
#define IDC_MANAGEGROUPS_INFO           1177
#define IDC_SPELL_OPTIONUKIZE           1178
#define IDC_SPELL_OPTIONLEGAL           1179
#define IDC_SPELL_OPTIONFINANCIAL       1180
#define IDC_SPELL_OPTIONMEDICAL         1181
#define IDC_SPELL_OPTIONLANGUAGE        1182
#define IDC_SPELL_OPTIONSPD             1183
#define IDC_SPELL_OPTIONSCLEAR          1184
#define IDC_SPELL_OPTIONSEDITPD         1185
#define IDC_SPELL_OPTIONSPDNEW          1186
#define IDC_SPELL_OPTIONSSUGG           1187
#define IDC_SPELL_OPTIONSCAPS           1188
#define IDC_SPELL_OPTIONSSTR            1189
#define IDC_SPELL_OPTIONSACCENT         1190
#define IDC_SPELL_OPTIONSNOACCENT       1191
#define IDC_SPELL_NEWDIC                1192
#define IDC_SPELL_EDITDICLIST           1193
#define IDC_SPELL_EDITDELETE            1194
#define IDC_SPELL_EDITSELALL            1195
#define IDC_SPELL_EDITDESELALL          1196
#define IDC_VERIFY_EXACT                1197
#define IDC_VERIFY_MIN                  1198
#define IDC_RECONCILE_LEVEL             1199
#define IDC_RECONCILE_NOSPLIT           1200
#define IDC_RECONCILE_PROTECT           1201
#define IDC_RECONCILE_SEPARATOR         1202
#define IDC_COMPRESS_REMDEL             1208
#define IDC_COMPRESS_REMEMPTY           1209
#define IDC_COMPRESS_REMDUP             1210
#define IDC_COMPRESS_CONSOLIDATE        1211
#define IDC_COMPRESS_REMGEN             1212
#define IDC_ALTER_ALLREFS               1213
#define IDC_ALTER_RANGEREF              1214
#define IDC_ALTER_RANGESTART            1216
#define IDC_ALTER_RANGENED              1217
#define IDC_ALTER_PATTERN               1218
#define IDC_ALTER_ADJONLY               1219
#define IDC_ALTER_REMOVE                1220
#define IDC_ALTER_HOLDHIGHER            1221
#define IDC_ALTER_ADJUSTMENT            1222
#define IDC_STATISTICS_RESULT           1223
#define IDC_COUNT_PAGESTART             1224
#define IDC_COUNT_PAGEEND               1225
#define IDC_COUNT_RESULT                1226
#define IDC_REFSYNTAX_PSEP              1227
#define IDC_REFSYNTAX_PCONN             1228
#define IDC_REFSYNTAX_CLEAD             1229
#define IDC_REFSYNTAX_CSEP              1230
#define IDC_REFSYNTAX_CGENERAL          1231
#define IDC_MARGCOL_TOP                 1232
#define IDC_MARGCOL_LEFT                1233
#define IDC_MARGCOL_BOTTOM              1234
#define IDC_MARGCOL_RIGHT               1235
#define IDC_MARGCOL_FACING              1236
#define IDC_MARGCOL_COLUMNS             1237
#define IDC_MARGCOL_GUTTER              1238
#define IDC_MARGCOL_NEVER               1239
#define IDC_MARGCOL_NEWPAGE             1240
#define IDC_MARGCOL_NEWCOLUMN           1241
#define IDC_MARGCOL_LEVEL               1242
#define IDC_MARGCOL_APPEND              1243
#define IDC_MARGCOL_STYLE               1244
#define IDC_MARGCOL_UNIT                1245
#define IDC_MARGCOL_LEFTTEXT            1246
#define IDC_MARGCOL_RIGHTTEXT           1247
#define IDC_HEADFOOT_TAB                1248
#define IDC_HEADFOOT_LEFT               1249
#define IDC_HEADFOOT_RIGHT              1250
#define IDC_HEADFOOT_CENTER             1251
#define IDC_HEADFOOT_FONT               1252
#define IDC_HEADFOOT_SIZE               1253
#define IDC_HEADFOOT_STYLE              1254
#define IDC_HEADFOOT_LONG               1255
#define IDC_HEADFOOT_SHORT              1256
#define IDC_HEADFOOT_TIME               1257
#define IDC_HEADFOOT_PAGENUM            1258
#define IDC_HEADFOOT_COPY               1259
#define IDC_GROUPENTRIES_NUMSYM         1260
#define IDC_GROUPENTRIES_TITLE          1261
#define IDC_GROUPENTRIES_FONT           1262
#define IDC_GROUPENTRIES_STYLE          1263
#define IDC_STYLAY_INDENTED             1264
#define IDC_STYLAY_RUNIN                1265
#define IDC_STYLAY_RUNLEVEL             1267
#define IDC_STYLAY_STYLEMOD             1268
#define IDC_STYLAY_INDENTTYPE           1269
#define IDC_STYLAY_TAB                  1270
#define IDC_STYLAY_EMSPACE              1271
#define IDC_STYLAY_ABSOLUTE             1272
#define IDC_STYLAY_LEADINDENT           1273
#define IDC_STYLAY_RUNINDENT            1274
#define IDC_STYLAY_AUTO                 1275
#define IDC_STYLAY_LSPACE               1276
#define IDC_STYLAY_LSPMAIN              1277
#define IDC_STYLAY_LSPGROUP             1278
#define IDC_STYLAY_ADJQUOTE             1279
#define IDC_STYLAY_ADJSTYLE             1280
#define IDC_STYLAY_INDUNIT              1281
#define IDC_STYLAY_COLLAPSELEVEL        1282
#define IDC_STYLAY_SPACING              1283
#define IDC_STYLAY_LSPUNIT              1284
#define IDC_HEADING_TRAILPUNCT          1284
#define IDC_HEADING_FONT                1285
#define IDC_HEADING_STYLE               1286
#define IDC_HEADING_TAB                 1287
#define IDC_CROSSREF_XLEAD              1288
#define IDC_CROSSREF_XALEAD             1289
#define IDC_CROSSREF_XTRAIL             1290
#define IDC_CROSSREF_XATRAIL            1291
#define IDC_CROSSREF_PSTYLE             1292
#define IDC_CROSSREF_BSTYLE             1293
#define IDC_CROSSREF_XAPOSITION         1294
#define IDC_CROSSREF_TAB                1295
#define IDC_CROSSREF_ORDER              1296
#define IDC_CROSSREF_POSPROMPT          1297
#define IDC_CROSSREF_XPOSITION          1298
#define IDC_PAGEREFS_CONNECT            1299
#define IDC_PAGEREFS_CONFLATE           1300
#define IDC_PAGEREFS_NOABBREV           1301
#define IDC_PAGEREFS_SUPPRESS           1304
#define IDC_PAGEREFS_SUPPRESSTO         1305
#define IDC_PAGEREFS_CONCAT             1306
#define IDC_PAGEREFS_JUSTIFY            1307
#define IDC_PAGEREFS_SINGLE             1308
#define IDC_PAGEREFS_MULTIPLE           1309
#define IDC_PAGEREFS_AFTER              1310
#define IDC_PAGEREFS_SORT               1311
#define IDC_PAGEREFS_STYLE              1312
#define IDC_PAGEREFS_LEADER             1313
#define IDC_REFSYNTAX_CSUBHEAD          1314
#define IDC_PAGEREFS_HIDEDUPLICATES     1314
#define IDC_TEXTSTYLE_BOLD              1315
#define IDC_TEXTSTYLE_ITALIC            1316
#define IDC_TEXTSTYLE_ULINE             1317
#define IDC_TEXTSTYLE_SMALL             1318
#define IDC_TEXTSTYLE_NCAP              1319
#define IDC_TEXTSTYLE_ICAP              1320
#define IDC_TEXTSTYLE_ALLCAP            1321
#define IDC_TEXTSTYLE_AUTO              1322
#define IDC_LOCATORSTYLE_BOLD           1323
#define IDC_LOCATORSTYLE_ITALIC         1324
#define IDC_LOCATORSTYLE_ULINE          1325
#define IDC_LOCATORSTYLE_SMALL          1326
#define IDC_LOCATORSTYLE_TAB            1327
#define IDC_AUTOGEN_SEE                 1330
#define IDC_FINDREP_FONT                1334
#define IDC_FINDREP_BOLD                1335
#define IDC_FINDREP_ITALIC              1336
#define IDC_FINDREP_ULINE               1337
#define IDC_FINDREP_SMALL               1338
#define IDC_FINDREP_NORMAL              1339
#define IDC_FINDREP_SUPER               1340
#define IDC_FINDREP_SUB                 1341
#define IDC_TAGS_MAINMENU               1346
#define IDC_TAGS_MAINNEW                1347
#define IDC_TAGS_MAINDUP                1348
#define IDC_TAGS_MAINDELETE             1349
#define IDC_TAGS_MAINEDIT               1350
#define IDC_TAG_SETNAME                 1351
#define IDC_TAG_BOLDON                  1352
#define IDC_TAG_BOLDOFF                 1353
#define IDC_TAG_ITALON                  1354
#define IDC_TAG_ITALOFF                 1355
#define IDC_TAG_ULINEON                 1356
#define IDC_TAG_ULINEOFF                1357
#define IDC_TAG_SMALLON                 1358
#define IDC_TAG_SMALLOFF                1359
#define IDC_TAG_SUPERON                 1360
#define IDC_TAG_SUPEROFF                1361
#define IDC_TAG_SUBON                   1362
#define IDC_TAG_SUBOFF                  1363
#define IDC_TAG_BION                    1364
#define IDC_TAG_BIOFF                   1365
#define IDC_PREFS_PEDITPASTEALL         1366
#define IDC_PREFS_PEDITPASTESTYLE       1367
#define IDC_PREFS_PEDITPASTEPLAIN       1368
#define IDC_FP1                         1448
#define IDC_FP2                         1449
#define IDC_FP3                         1450
#define IDC_FP4                         1451
#define IDC_FP5                         1452
#define IDC_FP6                         1453
#define IDC_FP7                         1454
#define IDC_FP8                         1455
#define IDC_FP9                         1456
#define IDC_FP10                        1457
#define IDC_FP11                        1458
#define IDC_FP12                        1459
#define IDC_FC1                         1460
#define IDC_FCE1                        1461
#define IDC_FC2                         1462
#define IDC_FCE2                        1463
#define IDC_FC3                         1464
#define IDC_FCE3                        1465
#define IDC_FC4                         1466
#define IDC_FCE4                        1467
#define IDC_FC5                         1468
#define IDC_FCE5                        1469
#define IDC_FC6                         1470
#define IDC_FCE6                        1471
#define IDC_FC7                         1472
#define IDC_FCE7                        1473
#define IDC_FC8                         1474
#define IDC_FCE8                        1475
#define IDC_FC9                         1476
#define IDC_FCE9                        1477
#define IDC_FC10                        1478
#define IDC_FCE10                       1479
#define IDC_FC11                        1480
#define IDC_FCE11                       1481
#define IDC_FC12                        1482
#define IDC_FCE12                       1483
#define IDC_TAG_STRUCTBEG               1486
#define IDC_TAG_STRUCTEND               1487
#define IDC_TAG_STRUCTGROUP             1488
#define IDC_TAG_STRUCTGROUPEND          1489
#define IDC_TAG_STRUCTAHEAD             1490
#define IDC_TAG_STRUCTAHEADEND          1491
#define IDC_TAG_L1S                     1492
#define IDC_TAG_L2S                     1493
#define IDC_TAG_L3S                     1494
#define IDC_TAG_L4S                     1495
#define IDC_TAG_L5S                     1496
#define IDC_TAG_L6S                     1497
#define IDC_TAG_L7S                     1498
#define IDC_TAG_L8S                     1499
#define IDC_TAG_L9S                     1500
#define IDC_TAG_L10S                    1501
#define IDC_TAG_L11S                    1502
#define IDC_TAG_L12S                    1503
#define IDC_TAG_L13S                    1504
#define IDC_TAG_L14S                    1505
#define IDC_TAG_L15S                    1506
#define IDC_TAG_L1E                     1507
#define IDC_TAG_L2E                     1508
#define IDC_TAG_L3E                     1509
#define IDC_TAG_L4E                     1510
#define IDC_TAG_L5E                     1511
#define IDC_TAG_L6E                     1512
#define IDC_TAG_L7E                     1513
#define IDC_TAG_L8E                     1514
#define IDC_TAG_L9E                     1515
#define IDC_TAG_L10E                    1516
#define IDC_TAG_L11E                    1517
#define IDC_TAG_L12E                    1518
#define IDC_TAG_L13E                    1519
#define IDC_TAG_L14E                    1520
#define IDC_TAG_L15E                    1521
#define IDC_TAG_PAGEREF                 1522
#define IDC_TAG_PAGEREFEND              1523
#define IDC_TAG_CROSSREF                1524
#define IDC_TAG_CROSSREFEND             1525
#define IDC_ASCIIP1                     1526
#define IDC_ASCIIC1                     1527
#define IDC_ASCIIP2                     1528
#define IDC_ASCIIC2                     1529
#define IDC_ASCIIP3                     1530
#define IDC_ASCIIC3                     1531
#define IDC_ASCIIP4                     1532
#define IDC_ASCIIC4                     1533
#define IDC_ASCIIP5                     1534
#define IDC_ASCIIC5                     1535
#define IDC_ASCIIP6                     1536
#define IDC_ASCIIC6                     1537
#define IDC_ASCIIP7                     1538
#define IDC_ASCIIC7                     1539
#define IDC_ASCIIP8                     1540
#define IDC_ASCIIC8                     1541
#define IDC_TAG_ENDLINE                 1542
#define IDC_TAG_ENDPARA                 1543
#define IDC_TAG_TAB                     1544
#define IDC_TAG_UNIPREFIX               1545
#define IDC_TAG_UNISUFFIX               1546
#define IDC_TAG_BODY                    1547
#define IDC_TAGS_EXTENSION              1548
#define IDC_FONTSUB_LIST                1548
#define IDC_TAG_UNIDECIMAL              1549
#define IDC_TAG_UNIHEXADECIMAL          1550
#define IDC_FONTSUB_PREFERRED           1550
#define IDC_FONTSUB_SUBS                1551
#define IDC_FONTSUB_CHECK               1552
#define IDC_HOTKEY1                     1555
#define IDC_HOTKEY2                     1556
#define IDC_HOTKEY3                     1557
#define IDC_HOTKEY4                     1558
#define IDC_HOTKEY5                     1559
#define IDC_HOTKEY6                     1560
#define IDC_HOTKEY7                     1561
#define IDC_HOTKEY8                     1562
#define IDC_HOTKEY9                     1563
#define IDC_HOTKEY10                    1564
#define IDC_HOTKEYTEXT1                 1565
#define IDC_HOTKEYTEXT2                 1566
#define IDC_HOTKEYTEXT3                 1567
#define IDC_HOTKEYTEXT4                 1568
#define IDC_HOTKEYTEXT5                 1569
#define IDC_HOTKEYTEXT6                 1570
#define IDC_HOTKEYTEXT7                 1571
#define IDC_HOTKEYTEXT8                 1572
#define IDC_HOTKEYTEXT9                 1573
#define IDC_HOTKEYTEXT10                1574
#define IDC_FORMWRITE_USEPROMPT         1575
#define IDC_FORMWRITE_USESTYLE          1576
#define IDC_FORMWRITE_USETAB            1577
#define IDC_TAGS_SUPPRESSREFS           1577
#define IDC_FORMWRITE_USEOTHER          1578
#define IDC_FORMWRITE_USEOTHERTEXT      1579
#define IDC_FORMWRITE_ALL               1580
#define IDC_FORMWRITE_PAGE              1581
#define IDC_FORMWRITE_SELECT            1582
#define IDC_FORMWRITE_RECORDS           1583
#define IDC_FORMWRITE_PSTART            1584
#define IDC_FORMWRITE_PEND              1585
#define IDC_FORMWRITE_RSTART            1586
#define IDC_FORMWRITE_REND              1587
#define IDC_HEADING_SUPPRESS            1588
#define IDC_PAGEREFS_SUPPRESSALL        1589
#define IDC_CROSSREF_SUPPRESS           1590
#define IDC_STYLAY_COLLAPSE             1592
#define IDC_REFSYNTAX_MAXVAL            1597
#define IDC_REFSYNTAX_MAXRANGE          1598
#define IDC_REPSTYLE_BOLDIG             1601
#define IDC_REPSTYLE_BOLDAP             1602
#define IDC_REPSTYLE_BOLDREM            1603
#define IDC_REPSTYLE_ITALIG             1604
#define IDC_REPSTYLE_ITALAP             1605
#define IDC_REPSTYLE_ITALREM            1606
#define IDC_REPSTYLE_ULINEIG            1607
#define IDC_REPSTYLE_ULINEAP            1608
#define IDC_REPSTYLE_ULINEREM           1609
#define IDC_REPSTYLE_FONTIG             1610
#define IDC_REPSTYLE_FONTSET            1611
#define IDC_REPSTYLE_FONT               1612
#define IDC_REPSTYLE_SMALLIG            1616
#define IDC_REPSTYLE_SMALLAP            1617
#define IDC_REPSTYLE_SMALLREM           1618
#define IDC_REPSTYLE_SUPIG              1619
#define IDC_REPSTYLE_SUPAP              1620
#define IDC_REPSTYLE_SUPREM             1621
#define IDC_REPSTYLE_SUBIG              1622
#define IDC_REPSTYLE_SUBAP              1623
#define IDC_REPSTYLE_SUBREM             1624
#define IDC_GROUPINFO_NAME              1625
#define IDC_GROUPINFO_RECNUM            1626
#define IDC_GROUPINFO_DATE              1627
#define IDC_GROUPINFO_METHOD            1628
#define IDC_GROUPINFO_CHANGES           1629
#define IDC_GROUPINFO_WORD              1630
#define IDC_GROUPINFO_CASE              1631
#define IDC_GROUPINFO_PATTERN           1632
#define IDC_GROUPINFO_EVAL              1633
#define IDC_GROUPINFO_NOT               1634
#define IDC_GROUPINFO_TEXT              1635
#define IDC_GROUPINFO_ANDOR             1636
#define IDC_GROUPINFO_FIELD             1637
#define IDC_GROUPINFO_ATTRIB            1638
#define IDC_SS_NORMAL                   1650
#define IDC_SS_SUPER                    1651
#define IDC_SS_SUB                      1652
#define IDC_SS_ADD                      1653
#define IDC_SS_DELETE                   1654
#define IDC_SS_REVERT                   1655
#define IDC_SS_BOLD                     1656
#define IDC_SS_ITALIC                   1657
#define IDC_SS_ULINE                    1658
#define IDC_SS_SMALL                    1659
#define IDC_SS_LIST                     1660
#define IDC_USERID                      1661
#define IDC_ARCHIVE_INCLUDE             1662
#define IDC_ARCHIVE_NEW                 1663
#define IDC_ABBREV_NAME                 1664
#define IDC_CHARTOOL_LIST               1665
#define IDC_CHARTOOL_FONT               1666
#define IDC_CHARTOOL_SHORTCUT           1667
#define IDC_CODETRANSG                  1668
#define IDC_CODETRANSH                  1669
#define IDC_SPELL_START                 1680
#define IDC_SPELL_STOP                  1681
#define IDC_COUNT_START                 1682
#define IDC_GENERIC_DONE                1683
#define IDC_STATISTICS_GO               1684
#define IDC_CHARTOOL_INSERT             1686
#define IDC_FIND_FINDSTART              1687
#define IDC_FIND_FINDSTOP               1688
#define IDC_REPLACE_REPALL              1689
#define IDC_SAVEAS_OPTIONS              1690
#define IDC_PREFS_PFORMSTYLE            1691
#define IDC_PREFS_PFORMTAB              1692
#define IDC_PREFS_PFORMOTHER            1693
#define IDC_PREFS_PFORMOTHERTEXT        1694
#define IDC_PREFS_PFORMEMBED            1695
#define IDC_PREFS_PFORM_UTF8            1696
#define IDC_PREFS_PFORM_NATIVE          1697
#define IDC_PASSWORD                    1698
#define IDC_FORMWRITE_SUPPRESS          1699
#define IDC_PPREFS_FILE_SHOWCDX         1700
#define IDC_PPREFS_FILE_SHOWSTL         1701
#define IDC_PPREFS_FILE_SHOWCTG         1702
#define IDC_PPREFS_FILE_SHOWABR         1703
#define IDC_PPREFS_FILE_SHOWUDC         1704
#define IDC_PPREFS_FILE_SETCDX          1705
#define IDC_PPREFS_FILE_SETSTL          1706
#define IDC_PPREFS_FILE_SETCTG          1707
#define IDC_PPREFS_FILE_SETABR          1708
#define IDC_PPREFS_FILE_SETUDC          1709
#define IDC_PPREFS_ADM_PWD1             1710
#define IDC_PPREFS_ADM_PWD2             1711
#define IDC_PPREFS_ADM_REQID            1712
#define IDC_PPREFS_ADM_VALID            1713
#define IDC_PPREFS_ADM_IDFILE           1714
#define IDC_PPREFS_ADM_TAB              1715
#define IDC_PPREFS_ADM_OPENDEF          1716
#define IDC_PPREFS_ADM_SETDEF           1717
#define IDC_PPREFS_ADM_CHANGEDEF        1718
#define IDC_PPREFS_ADM_READONLY         1719
#define IDC_PPREFS_ADM_PERMITWRITE      1720
#define IDC_PPREFS_ADM_MULTIPLE         1721
#define IDC_HEADING_LEADTEXT            1722
#define IDC_WRITE_UNFORMMINFIELD        1723
#define IDC_WRITE_UNFORMMINFIELDPROMPT  1724
#define IDC_HEADFOOT_NUMFORMAT          1731
#define IDC_MACRO_SETNAME               1732
#define IDC_RECONCILE_CONVERT           1733
#define IDC_RECONCILE_REMOVE            1734
#define IDC_RECONCILE_PRESERVE          1737
#define IDC_VERIFY_CROSSREF             1738
#define IDC_VERIFY_LOCATOR              1739
#define IDC_VERIFY_LOCATORLIMIT         1740
#define IDC_FIND_ONLYAMONG              1742
#define IDC_FIND_NOTAMONG               1743
#define IDC_FIND_TAGRECLEVEL            1744
#define IDC_MANAGECROSS_CCOUNT          1747
#define IDC_MANAGECROSS_GENERATE        1748
#define IDC_MANAGECROSS_CONVERT         1749
#define IDC_SORT_TEXT_SIMPLE            1750
#define IDC_RECORDSTRUCT_REQUIRED       1751
#define IDC_PREFS_PEDIT_SMARTFLIP       1752
#define IDC_PREFS_PEDIT_AUTORANGE       1753
#define IDC_PREFS_PTEXTLABELC1          1754
#define IDC_PREFS_PTEXTLABELC2          1755
#define IDC_PREFS_PTEXTLABELC3          1756
#define IDC_PREFS_PTEXTLABELC4          1757
#define IDC_COMPRESS_IGNORELABELS       1757
#define IDC_PREFS_PTEXTLABELC5          1758
#define IDC_PREFS_PTEXTLABELC6          1759
#define IDC_PREFS_PTEXTLABELC7          1760
#define IDC_FILTER_ON                   1761
#define IDC_FILTER_LABEL0               1762
#define IDC_SPELL_EDITDICCOUNT          1762
#define IDC_FILTER_LABEL1               1763
#define IDC_PPREFS_FILE_CLEARCDX        1763
#define IDC_FILTER_LABEL2               1764
#define IDC_FILTER_LABEL3               1765
#define IDC_FILTER_LABEL4               1766
#define IDC_FILTER_LABEL5               1767
#define IDC_FILTER_LABEL6               1768
#define IDC_PPREFS_FILE_CLEARSTL        1768
#define IDC_SORT_LANGUAGE               1768
#define IDC_FILTER_LABEL7               1769
#define IDC_PPREFS_FILE_CLEARABR        1769
#define IDC_PPREFS_FILE_CLEARCTG        1770
#define IDC_PPREFS_FILE_CLEARUDC        1771
#define IDC_CREDITTEXT                  1772
#define IDC_ABOUTCINDEX_CREDITS         1773
#define IDC_TAGS_MAINTAB                1774
#define IDC_TAGS_NESTHEADINGS           1775
#define IDC_TAGS_INDIVIDUALREFS         1776
#define IDC_FA_NONE                     1778
#define IDC_FA_ID                       1779
#define IDC_FA_NAME                     1780
#define IDC_CROSSREF_                   1782
#define IDC_CROSSREF_PREFIXSTYLECHECK   1782
#define IDC_EDIT1                       1784
#define IDC_GROUPENTRIES_ALLNUMBERS     1784
#define IDC_FW_LIST                     1784
#define IDC_SPLIT_USERPATTERN           1784
#define IDC_SORT_SUB_SOURCE             1784
#define IDC_SORT_SUB_REP                1785
#define IDC_GROUPENTRIES_NUMBERSANDSYMBOLS 1785
#define IDC_CHECK_R_MINMATCHES          1785
#define IDC_EDIT2                       1785
#define IDC_FORM_L0                     1785
#define IDC_GROUPENTRIES_ALLSYMBOLS     1786
#define IDC_FORM_L1                     1786
#define IDC_PREFS_PEDITCACCEPT          1787
#define IDC_FORM_L2                     1787
#define IDC_PREFS_PEDITCWARN            1788
#define IDC_FORM_L3                     1788
#define IDC_PREFS_PEDITCFORBID          1789
#define IDC_FORM_L4                     1789
#define IDC_WRITEUNFORM_UTF8            1790
#define IDC_FORM_L5                     1790
#define IDC_WRITEUNFORM_ANSI            1791
#define IDC_FORM_L6                     1791
#define IDC_PREFS_PRTEXTSIZE            1792
#define IDC_FORM_L7                     1792
#define IDC_TAGS_LEVELATTRIBUTE         1793
#define IDC_FORM_L8                     1793
#define IDC_CHECK1                      1794
#define IDC_SPLIT_MARKRECORDS           1794
#define IDC_FORM_L9                     1794
#define IDC_SORT_LEFT_RIGHT             1794
#define IDC_FORM_L10                    1795
#define IDC_SPLIT_REMOVESTYLES          1796
#define IDC_FORM_L11                    1796
#define IDC_FORM_L12                    1797
#define IDC_FORM_L13                    1798
#define IDC_SPLIT_PATTERN               1799
#define IDC_FORM_L14                    1799
#define IDC_BUTTON1                     1800
#define IDC_SPLIT_PREVIEW               1800
#define IDC_SORT_SUBSTITUTE             1800
#define IDC_SORT_SUB_ADD                1800
#define IDC_FORM_L15                    1800
#define IDC_CHECK_B_MISUSED             1801
#define IDC_CHECK_B_PUNCTSPACE          1802
#define IDC_CHECK_B_MISSINGSPACE        1803
#define IDC_CHECK_B_UNBALANCEDPAREN     1804
#define IDC_CHECK_B_UNBALANCEDQUOTE     1805
#define IDC_CHECK_H_ORPHANDEPTH         1806
#define IDC_CHECK_H_INCONSISTENTCAPS    1807
#define IDC_CHECK_H_INCONSISTENTSTYLE   1808
#define IDC_CHECK_H_INCONSISTENTPUNCT   1809
#define IDC_CHECK_H_INCONSISTENTPLURALS 1810
#define IDC_CHECK_H_INCONSISTENTPAREN   1811
#define IDC_CHECK_H_ORPHANEDSUBHEAD     1812
#define IDC_CHECK_R_EMPTYPAGE           1813
#define IDC_CHECK_H_INCONSISTENTLEADPREP 1813
#define IDC_CHECK_R_TOOMANYPAGE         1814
#define IDC_CHECK_R_HEADINGLEVEL        1815
#define IDC_CHECK_R_VERIFY              1816
#define IDC_CHECK_R_PAGEREFLIMIT        1817
#define IDC_CHECK_R_EXACTMATCH          1818
#define IDC_FINDSTYLE_BOLDIG            1819
#define IDC_FINDSTYLE_BOLDAP            1820
#define IDC_FINDSTYLE_BOLDREM           1821
#define IDC_FINDSTYLE_ITALIG            1822
#define IDC_FINDSTYLE_ITALAP            1823
#define IDC_FINDSTYLE_ITALREM           1824
#define IDC_FINDSTYLE_ULINEIG           1825
#define IDC_FINDSTYLE_ULINEAP           1826
#define IDC_FINDSTYLE_ULINEREM          1827
#define IDC_FINDSTYLE_SMALLIG           1828
#define IDC_FINDSTYLE_SMALLAP           1829
#define IDC_FINDSTYLE_SMALLREM          1830
#define IDC_FINDSTYLE_SUPIG             1831
#define IDC_FINDSTYLE_SUPAP             1832
#define IDC_FINDSTYLE_SUPREM            1833
#define IDC_FINDSTYLE_SUBIG             1834
#define IDC_FINDSTYLE_SUBAP             1835
#define IDC_FINDSTYLE_SUBREM            1836
#define IDC_FINDSTYLE_FONTIG            1837
#define IDC_FINDSTYLE_FONTSET           1838
#define IDC_FINDSTYLE_FONTREM           1839
#define IDC_FINDSTYLE_FONT              1840
#define IDC_SPLASH_IMAGE                1841
#define IDC_LIST1                       1843
#define IDC_SORT_SUB_LIST               1843
#define IDC_SORT_SUB_REMOVE             1844
#define IDC_FORMWRITE_STYLENAMES        1845
#define IDC_FORM_FIELDNAMES             1846
#define IDC_FORM_TABLENAMES             1847
#define IDC_TAG_UTF8                    1848
#define IDM_FILE_NEW                    40001
#define IDM_FILE_OPEN                   40002
#define IDM_FILE_CLOSE                  40003
#define IDM_FILE_SAVE                   40004
#define IDM_FILE_SAVEAS                 40005
#define IDM_FILE_SAVEACOPYAS            40006
#define IDM_FILE_SAVEFORMAT             40007
#define IDM_FILE_IMPORT                 40008
#define IDM_FILE_PAGESETUP              40009
#define IDM_FILE_PRINT                  40010
#define IDM_FILE_EXIT                   40011
#define IDM_EDIT_UNDO                   40020
#define IDM_EDIT_CUT                    40022
#define IDM_EDIT_COPY                   40023
#define IDM_EDIT_PASTE                  40024
#define IDM_EDIT_CLEAR                  40025
#define IDM_EDIT_SELECTALL              40026
#define IDM_EDIT_NEWRECORD              40027
#define IDM_EDIT_EDITRECORD             40028
#define IDM_EDIT_DUPLICATE              40029
#define IDM_EDIT_DELETE                 40030
#define IDM_EDIT_TAG                    40031
#define IDM_EDIT_FIND                   40032
#define IDM_EDIT_REPLACE                40033
#define IDM_EDIT_NEWGROUP               40034
#define IDM_EDIT_SAVEGROUP              40035
#define IDM_EDIT_PREFERENCES            40036
#define IDM_EDIT_NEWABBREV              40037
#define IDM_DOCUMENT_MARGINSCOLUMNS     40043
#define IDM_DOCUMENT_HEADERSFOOTER      40044
#define IDM_DOCUMENT_GROUPINGENTRIES    40045
#define IDM_DOCUMENT_STYLELAYOUT        40046
#define IDM_DOCUMENT_HEADINGS           40047
#define IDM_DOCUMENT_CROSSREFERENCES    40048
#define IDM_DOCUMENT_PAGEREFERENCES     40049
#define IDM_DOCUMENT_STYLEDSTRINGS      40050
#define IDM_DOCUMENT_RECORDSTRUCTURE    40051
#define IDM_DOCUMENT_REFERENCESYNTAX    40052
#define IDM_TOOLS_CHECKSPELLING         40053
#define IDM_TOOLS_VERIFYCROSSREFERENCES 40054
#define IDM_TOOLS_RECONCILEHEADINGS     40055
#define IDM_TOOLS_GENERATECROSSREFERENCES 40056
#define IDM_TOOLS_ALTERREFERENCES       40057
#define IDM_TOOLS_SORT                  40058
#define IDM_TOOLS_COMPRESS              40059
#define IDM_TOOLS_EXPAND                40060
#define IDM_TOOLS_COUNTRECORDS          40061
#define IDM_TOOLS_INDEXSTATISTICS       40062
#define IDM_TOOLS_FONTS                 40063
#define IDM_TOOLS_MARKUPTAGS            40064
#define IDM_TOOLS_HOTKEYS               40065
#define IDM_TOOLS_RECORDKEY             40066
#define IDM_TOOLS_PLAYKEY               40067
#define IDM_TOOLS_GROUPS                40068
#define IDM_VIEW_GOTO                   40106
#define IDM_VIEW_ALLRECORDS             40107
#define IDM_VIEW_NEWRECORDS             40108
#define IDM_VIEW_GROUP                  40109
#define IDM_VIEW_TEMPORARYGROUP         40110
#define IDM_VIEW_FULLFORMAT             40111
#define IDM_VIEW_DRAFTFORMAT            40112
#define IDM_VIEW_SUMMARY                40113
#define IDM_VIEW_UNFORMATTED            40114
#define IDM_VIEW_SHOWNUMBERS            40115
#define IDM_VIEW_VIEWDEPTH              40116
#define IDM_VIEW_WRAPLINES              40117
#define IDM_VIEW_SHOWSORTED             40118
#define IDM_VIEW_ABBREVIATIONS          40120
#define IDM_VIEW_SHOWBYEXPANSION        40121
#define IDM_VIEW_VIEWDEPTH_FIRST        40131
#define IDM_WINDOW_CLIPBOARD            40149
#define IDM_WINDOW_CASCADE              40150
#define IDM_WINDOW_TILE                 40151
#define IDM_WINDOW_CLOSEALL             40152
#define IDM_WINDOW_ARRANGEICONS         40153
#define IDM_HELP_ABOUT                  40170
#define IDM_COMBO_FONT                  40180
#define IDM_COMBO_SIZE                  40181
#define IDM_STYLE_REGULAR               40190
#define IDM_STYLE_BOLD                  40191
#define IDM_STYLE_ITALIC                40192
#define IDM_STYLE_UNDERLINE             40193
#define IDM_STYLE_SMALLCAPS             40194
#define IDM_STYLE_SUPER                 40195
#define IDM_STYLE_SUB                   40196
#define IDM_STYLE_INITIALCAPS           40197
#define IDM_STYLE_UPPERCASE             40198
#define IDM_STYLE_LOWERCASE             40199
#define IDM_FONT_DEFAULT                40200
#define IDM_FONT_SYMBOLS                40201
#define IDM_FILE_RECENT1                40210
#define IDM_FILE_RECENT2                40211
#define IDM_FILE_RECENT3                40212
#define IDM_FILE_RECENT4                40213
#define IDM_FILE_RECENT5                40214
#define IDM_FILE_RECENT6                40215
#define IDM_FILE_RECENT7                40216
#define IDM_FILE_RECENT8                40217
#define IDM_FILE_RECENT9                40218
#define IDM_FILE_RECENT10               40219
#define IDM_FILE_RECENT11               40220
#define IDM_FILE_RECENT12               40221
#define IDM_FILE_STATIONERY             40222
#define IDPM_FILE                       40260
#define IDPM_EDIT                       40261
#define IDPM_VIEW                       40262
#define IDPM_CHARACTERS                 40263
#define IDPM_DOCUMENT                   40264
#define IDPM_TOOLS                      40265
#define IDPM_WINDOW                     40266
#define IDPM_HELP                       40267
#define IDPM_MODCONTEXT                 40300
#define IDPM_VIEWCONTEXT                40301
#define IDPM_LABEL                      40302
#define IDPM_VIEWGROUP                  40303
#define IDPM_VIEWDEPTH                  40304
#define IDPM_EDITTAG                    40305
#define IDPM_ABBREVIATIONS              40306
#define IDPM_ALIGNMENT                  40307
#define IDM_VIEW_GROUP_FIRST            40400
#define IDM_VIEW_GROUP_LAST             40499
#define IDM_HELP_TOPICS                 40517
#define IDB_MOD_BRACES                  40534
#define IDB_MOD_BRACKETS                40535
#define IDM_MACRO_1                     40554
#define IDM_MACRO_2                     40555
#define IDM_MACRO_3                     40556
#define IDM_MACRO_4                     40557
#define IDM_MACRO_5                     40558
#define IDM_MACRO_6                     40559
#define IDM_MACRO_7                     40560
#define IDM_MACRO_8                     40561
#define IDM_MACRO_9                     40562
#define IDM_MACRO_10                    40563
#define IDM_PMACRO_1                    40564
#define IDM_PMACRO_2                    40565
#define IDM_PMACRO_3                    40566
#define IDM_PMACRO_4                    40567
#define IDM_PMACRO_5                    40568
#define IDM_PMACRO_6                    40569
#define IDM_PMACRO_7                    40570
#define IDM_PMACRO_8                    40571
#define IDM_PMACRO_9                    40572
#define IDM_PMACRO_10                   40573
#define IDM_EDIT_FINDAGAIN              40575
#define IDM_EDIT_LABEL_SWITCH           40579
#define IDM_EDIT_LABEL0                 40580
#define IDM_EDIT_LABEL1                 40581
#define IDM_EDIT_LABEL2                 40582
#define IDM_EDIT_LABEL3                 40583
#define IDM_EDIT_LABEL4                 40584
#define IDM_EDIT_LABEL5                 40585
#define IDM_EDIT_LABEL6                 40586
#define IDM_EDIT_LABEL7                 40587
#define IDM_EDIT_LABEL8                 40588
#define IDB_MOD_PROPAGATE               40590
#define IDB_MOD_FLIP                    40598
#define IDB_MOD_FLIPX                   40599
#define IDB_MOD_HALFFLIP                40600
#define IDB_MOD_HALFFLIPX               40601
#define IDB_MOD_PREV                    40603
#define IDB_MOD_NEXT                    40604
#define IDB_MOD_REVERT                  40605
#define IDB_MOD_DUPNEW                  40606
#define IDB_VIEW_RUNIN                  40607
#define IDB_VIEW_INDENTED               40608
#define IDB_VIEW_SORTALPHA              40609
#define IDB_VIEW_SORTPAGE               40610
#define IDB_VIEW_SORTNONE               40611
#define IDM_VIEW_ATTRIBUTES             40638
#define IDM_EDIT_REDO                   40640
#define IDM_FILE_REVERT                 40646
#define IDM_HELP_CHECKFORUPDATES        40647
#define ID_FILE_REVERTTOSAVED           40648
#define ID_FILE_REVERTTOSAVED40649      40649
#define ID_FILE_REVERTTOSAVED40650      40650
#define IDM_EDIT_DEMOTE                 40651
#define ID_Menu                         40652
#define IDM_MOD_INCREMENT               40655
#define IDM_MOD_DECREMENT               40656
#define IDM_DOCUMENT_FLIPWORDS          40658
#define IDM_SWAPPARENS                  40662
#define IDM_EDIT_SWAPPARENS             40663
#define IDB_MOD_SWAPPAREN               40665
#define ID_PATTERNPOP_DUMMYENTRY        40667
#define IDM_TOOLS_ABBREV_ATTACH         40672
#define IDM_TOOLS_ABBREV_DETACH         40673
#define IDM_TOOLS_ABBREV_NEW            40674
#define IDM_TOOLS_ABBREV_EDIT           40675
#define IDM_ALIGNMENT                   40683
#define IDM_ALIGNMENT_NATURAL           40687
#define IDM_ALIGNMENT_LEFT              40688
#define IDM_ALIGNMENT_RIGHT             40689
#define IDM_TOOLS_SPLITHEADINGS         40691
#define IDM_TOOLS_CHECKINDEX            40692
#define ID_EDIT_DEMOTEHEADINGS          40693
#define ID_VIEWPOP_DEMOTEHEADINGS       40694
#define ID_VIEWPOP_REMOVEMARK           40702
#define IDM_EDIT_REMOVEMARK             40703

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        358
#define _APS_NEXT_COMMAND_VALUE         40704
#define _APS_NEXT_CONTROL_VALUE         1849
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
